# Generated by Django 2.1.1 on 2018-09-11 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_dated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
